'use client';
import { createEvents } from 'ics';
import jsPDF from 'jspdf';
import type { BusyBlock } from '@/types';

interface Props {
  freeBlocks: BusyBlock[];
  title?: string;
}

function toDateArray(iso: string): [number, number, number, number, number] {
  const d = new Date(iso);
  return [d.getUTCFullYear(), d.getUTCMonth() + 1, d.getUTCDate(), d.getUTCHours(), d.getUTCMinutes()];
}

export function ExportPanel({ freeBlocks, title = 'Availability' }: Props) {
  const significantSlots = freeBlocks.filter(
    (b) => !b.busy && new Date(b.end).getTime() - new Date(b.start).getTime() >= 3_600_000,
  );

  function downloadIcs() {
    if (significantSlots.length === 0) return;
    const { error, value } = createEvents(
      significantSlots.map((b) => ({
        title: 'Available',
        start: toDateArray(b.start),
        end: toDateArray(b.end),
        startInputType: 'utc' as const,
        endInputType: 'utc' as const,
      })),
    );
    if (error || !value) return;
    const blob = new Blob([value], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'availability.ics';
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadPdf() {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text(title, 14, 20);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Generated by CalShare — event details are never included.', 14, 28);

    const top5 = significantSlots.slice(0, 5);
    if (top5.length === 0) {
      doc.text('No free slots found.', 14, 40);
    } else {
      doc.setFontSize(11);
      doc.setTextColor(0);
      top5.forEach((b, i) => {
        const start = new Date(b.start).toLocaleString();
        const durationMin = Math.round(
          (new Date(b.end).getTime() - new Date(b.start).getTime()) / 60_000,
        );
        doc.text(`${i + 1}. ${start} (${durationMin} min)`, 14, 42 + i * 10);
      });
    }
    doc.save('availability.pdf');
  }

  return (
    <div className="flex flex-wrap gap-2">
      <button
        onClick={downloadIcs}
        disabled={significantSlots.length === 0}
        className="border rounded-lg px-3 py-1.5 text-sm hover:bg-gray-50 disabled:opacity-40 transition-colors"
      >
        Export .ics
      </button>
      <button
        onClick={downloadPdf}
        disabled={significantSlots.length === 0}
        className="border rounded-lg px-3 py-1.5 text-sm hover:bg-gray-50 disabled:opacity-40 transition-colors"
      >
        Export PDF
      </button>
    </div>
  );
}
